# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Tech Diary'  # Your Title
tagline: 'Just coding'  # A brief tagline for your site
email: zhao.zchen9@gmail.com
description: 
github_username:  zchen9
sidebar_image: /images/cover.jpg
timezone: 'Asia/Shanghai'
destination: ./_site

# Build settings
encoding: UTF-8
markdown: kramdown
#for publish
#highlighter: pygments
#for local
#highlighter: true
url: /code
baseurl: /code # the subpath of your site, e.g. /blog/
permalink: :title

#page
paginate: 15
paginate_path: "page:num"
plugins: [jekyll-paginate]
